
services:
  server:
    image: maven
    container_name: gestao_vagas_server
    volumes:
      - .:/app
    working_dir: /app
    command: mvn spring-boot:run
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestao_vagas
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: